version: "3.8"
services:
  server:
    image: jerryenebeli/blnk:0.7.4
    restart: unless-stopped
    ports:
      - "5001:5001"
    volumes:
      - ./blnk.json:/blnk.json
    healthcheck:
      test: ["CMD", "curl", "-f", "<http://localhost:5001/health>"]
      interval: 30s
      timeout: 10s
      retries: 3

  worker:
    image: jerryenebeli/blnk:0.7.4
    restart: unless-stopped
    entrypoint: ["blnk", "workers"]
    volumes:
      - ./blnk.json:/blnk.json
    depends_on:
      - server

  migration:
    image: jerryenebeli/blnk:0.7.4
    entrypoint: ["blnk", "migrate", "up"]
    volumes:
      - ./blnk.json:/blnk.json
    restart: "no"